// Mocks generated by Mockito 5.4.6 from annotations
// in spendwise/test/providers/expense_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:spendwise/models/transaction_model.dart' as _i2;
import 'package:spendwise/services/expense_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTransactionModel_0 extends _i1.SmartFake
    implements _i2.TransactionModel {
  _FakeTransactionModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExpenseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseService extends _i1.Mock implements _i3.ExpenseService {
  MockExpenseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TransactionModel>> getAllTransactions({
    int? page = 1,
    int? limit = 10,
    String? category,
    String? sortBy = 'date',
    String? sortOrder = 'desc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTransactions, [], {
              #page: page,
              #limit: limit,
              #category: category,
              #sortBy: sortBy,
              #sortOrder: sortOrder,
            }),
            returnValue: _i4.Future<List<_i2.TransactionModel>>.value(
              <_i2.TransactionModel>[],
            ),
          )
          as _i4.Future<List<_i2.TransactionModel>>);

  @override
  _i4.Future<dynamic> getMonthlyExpenses(int? month, int? year) =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyExpenses, [month, year]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> getDailyExpenses({DateTime? date}) =>
      (super.noSuchMethod(
            Invocation.method(#getDailyExpenses, [], {#date: date}),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<_i2.TransactionModel> createTransaction(
    _i2.TransactionModel? transaction,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTransaction, [transaction]),
            returnValue: _i4.Future<_i2.TransactionModel>.value(
              _FakeTransactionModel_0(
                this,
                Invocation.method(#createTransaction, [transaction]),
              ),
            ),
          )
          as _i4.Future<_i2.TransactionModel>);

  @override
  _i4.Future<void> updateTransaction(
    String? id,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTransaction, [id, updates]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.TransactionModel> getTransaction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTransaction, [id]),
            returnValue: _i4.Future<_i2.TransactionModel>.value(
              _FakeTransactionModel_0(
                this,
                Invocation.method(#getTransaction, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.TransactionModel>);

  @override
  _i4.Future<void> deleteTransaction(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTransaction, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
